#pragma once

#include "common/type.hpp"

namespace Terreate::Vulkan {

enum class DeviceFeatures : u64 {
  ROBUST_BUFFER_ACCESS = 1 << 0,
  FULL_DRAW_INDEX_UINT32 = 1 << 1,
  IMAGE_CUBE_ARRAY = 1 << 2,
  INDEPENDENT_BLEND = 1 << 3,
  GEOMETRY_SHADER = 1 << 4,
  TESSELLATION_SHADER = 1 << 5,
  SAMPLE_RATE_SHADING = 1 << 6,
  DUAL_SRC_BLEND = 1 << 7,
  LOGIC_OP = 1 << 8,
  MULTI_DRAW_INDIRECT = 1 << 9,
  DRAW_INDIRECT_FIRST_INSTANCE = 1 << 10,
  DEPTH_CLAMP = 1 << 11,
  DEPTH_BIAS_CLAMP = 1 << 12,
  FILL_MODE_NON_SOLID = 1 << 13,
  DEPTH_BOUNDS = 1 << 14,
  WIDE_LINES = 1 << 15,
  LARGE_POINTS = 1 << 16,
  ALPHA_TO_ONE = 1 << 17,
  MULTI_VIEWPORT = 1 << 18,
  SAMPLER_ANISOTROPY = 1 << 19,
  TEXTURE_COMPRESSIONETC2 = 1 << 20,
  TEXTURE_COMPRESSION_ASTC_LDR = 1 << 21,
  TEXTURE_COMPRESSIONBC = 1 << 22,
  OCCLUSION_QUERY_PRECISE = 1 << 23,
  PIPELINE_STATISTICS_QUERY = 1 << 24,
  VERTEX_PIPELINE_STORES_AND_ATOMICS = 1 << 25,
  FRAGMENT_STORES_AND_ATOMICS = 1 << 26,
  SHADER_TESSELLATION_AND_GEOMETRY_POINT_SIZE = 1 << 27,
  SHADER_IMAGE_GATHER_EXTENDED = 1 << 28,
  SHADER_STORAGE_IMAGE_EXTENDED_FORMATS = 1 << 29,
  SHADER_STORAGE_IMAGE_MULTISAMPLE = 1 << 30,
  SHADER_STORAGE_IMAGE_READ_WITHOUT_FORMAT = 1ULL << 31,
  SHADER_STORAGE_IMAGE_WRITE_WITHOUT_FORMAT = 1ULL << 32,
  SHADER_UNIFORM_BUFFER_ARRAY_DYNAMIC_INDEXING = 1ULL << 33,
  SHADER_SAMPLED_IMAGE_ARRAY_DYNAMIC_INDEXING = 1ULL << 34,
  SHADER_STORAGE_BUFFER_ARRAY_DYNAMIC_INDEXING = 1ULL << 35,
  SHADER_STORAGE_IMAGE_ARRAY_DYNAMIC_INDEXING = 1ULL << 36,
  SHADER_CLIP_DISTANCE = 1ULL << 37,
  SHADER_CULL_DISTANCE = 1ULL << 38,
  SHADER_FLOAT64 = 1ULL << 39,
  SHADER_INT64 = 1ULL << 40,
  SHADER_INT16 = 1ULL << 41,
  SHADER_RESOURCE_RESIDENCY = 1ULL << 42,
  SHADER_RESOURCE_MIN_LOD = 1ULL << 43,
  SPARSE_BINDING = 1ULL << 44,
  SPARSE_RESIDENCY_BUFFER = 1ULL << 45,
  SPARSE_RESIDENCY_IMAGE_2D = 1ULL << 46,
  SPARSE_RESIDENCY_IMAGE_3D = 1ULL << 47,
  SPARSE_RESIDENCY_2_SAMPLES = 1ULL << 48,
  SPARSE_RESIDENCY_4_SAMPLES = 1ULL << 49,
  SPARSE_RESIDENCY_8_SAMPLES = 1ULL << 50,
  SPARSE_RESIDENCY_16_SAMPLES = 1ULL << 51,
  SPARSE_RESIDENCY_ALIASED = 1ULL << 52,
  VARIABLE_MULTISAMPLE_RATE = 1ULL << 53,
  INHERITED_QUERIES = 1ULL << 54,
};

enum class MessageType {
  GENERAL = VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT,
  VALIDATION = VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT,
  PERFORMANCE = VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT,
  DEVICE_ADDRESS_BINDING =
      VK_DEBUG_UTILS_MESSAGE_TYPE_DEVICE_ADDRESS_BINDING_BIT_EXT,
};

enum class QueueType {
  GRAPHICS = VK_QUEUE_GRAPHICS_BIT,
  COMPUTE = VK_QUEUE_COMPUTE_BIT,
  TRANSFER = VK_QUEUE_TRANSFER_BIT,
  SPARSE_BINDING = VK_QUEUE_SPARSE_BINDING_BIT,
  PROTECTED = VK_QUEUE_PROTECTED_BIT,
  VIDEO_DECODE = VK_QUEUE_VIDEO_DECODE_BIT_KHR,
  VIDEO_ENCODE = VK_QUEUE_VIDEO_ENCODE_BIT_KHR,
  OPTICAL_FLOW = VK_QUEUE_OPTICAL_FLOW_BIT_NV,
};

} // namespace Terreate::Vulkan
