#pragma once

#include "common/type.hpp"

namespace Terreate::Vulkan {

enum class MessageType {
  GENERAL = VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT,
  VALIDATION = VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT,
  PERFORMANCE = VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT,
  DEVICE_ADDRESS_BINDING =
      VK_DEBUG_UTILS_MESSAGE_TYPE_DEVICE_ADDRESS_BINDING_BIT_EXT
};

enum class QueueType {
  GRAPHICS = VK_QUEUE_GRAPHICS_BIT,
  COMPUTE = VK_QUEUE_COMPUTE_BIT,
  TRANSFER = VK_QUEUE_TRANSFER_BIT,
  SPARSE_BINDING = VK_QUEUE_SPARSE_BINDING_BIT,
  PROTECTED = VK_QUEUE_PROTECTED_BIT,
  VIDEO_DECODE = VK_QUEUE_VIDEO_DECODE_BIT_KHR,
  VIDEO_ENCODE = VK_QUEUE_VIDEO_ENCODE_BIT_KHR,
  OPTICAL_FLOW = VK_QUEUE_OPTICAL_FLOW_BIT_NV,
};

} // namespace Terreate::Vulkan
